export const ENDPOINTS = {
  USERS: '/users',
  POSTS: '/posts',
  LOGIN: '/auth/login',
  ME: '/auth/me',
  REGISTER: '/auth/register',
  RESET_PASSWORD: '/auth/reset-password',
  WORKLOG: '/worklog',
  SKILLS: '/skill',
  ACTIVITIES: '/activity',
  RESOURCE: '/document',
  NOTIFICATIONS: '/notification',
  USER_PREFERENCES: '/users/me/preferences',
  STATS: 'dashboard/stats',
};
